const categoryMap = <String, String>{
  "Apparel": "服&ファッション小物",
  "Baby Product": "ベビー&マタニティ",
  "eBooks": "電子書籍",
  "Book": "本",
  "Books": "本",
  "CE": "家電&カメラ",
  "Photo": "家電&カメラ",
  "Photography": "家電&カメラ",
  "Home Theater": "家電&カメラ",
  "Wireless": "家電・カメラ・AV機器",
  "DVD": "DVD",
  "Grocery": "食品・飲料・お酒",
  "Alcoholic Beverage": "食品・飲料・お酒",
  "Health and Beauty": "ヘルス&ビューティー",
  "Beauty": "ビューティー",
  "Prestige Beauty": "ビューティー",
  "Home": "ホーム&キッチン",
  "Kitchen": "ホーム&キッチン",
  "Music": "ミュージック",
  "Office Product": "文房具・オフィス用品",
  "Shoes": "シューズ",
  "Software": "PCソフト",
  "Sports": "スポーツ&アウトドア",
  "Toy": "おもちゃ",
  "VHS": "ビデオ",
  "Video Games": "TVゲーム",
  "Video Game": "TVゲーム",
  "Watch": "腕時計",
  "MusicalInstruments": "楽器",
  "Musical Instruments": "楽器",
  "Hobby": "ホビー",
  "Hobbies": "ホビー",
  "DIY": "DIY・工具・ガーデン",
  "Home Improvement": "DIY・工具・ガーデン",
  "Personal Computer": "パソコン・周辺機器",
  "Major Appliances": "大型家電",
  "Digital Device Accessory": "タブレットPCアクセサリ",
  "Pet Products": "ペット用品",
  "Jewelry": "ジュエリー",
  "BISS Basic": "産業・研究開発用品",
  "Automotive Parts and Accessories": "車＆バイク",
  "Pantry": "パントリー", // TODO:
};
