# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    type_annotate_public_apis: false
    flutter_style_todos: false
    prefer_single_quotes: false
    use_build_context_synchronously: false