# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
#  enable-experiment:
#    - non-nullable
  exclude:
    - lib/*_original.dart
    - lib/generated_*.dart
    - lib/main_global_object_key.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/util/euc/*.dart
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    # Causes false positives (https://github.com/dart-lang/sdk/issues/41571
    top_level_function_literal_block: ignore
    # null-safe 対応後に削除
    import_of_legacy_library_into_null_safe: false

linter:
  rules:
    type_annotate_public_apis: false
    flutter_style_todos: false
    prefer_single_quotes: false
    sort_pub_dependencies: false