# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude:
    - lib/*_original.dart
    - lib/generated_*.dart
    - lib/main_global_object_key.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/util/euc/*.dart
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    type_annotate_public_apis: false
    flutter_style_todos: false
    prefer_single_quotes: false