targets:
  $default:
    builders:
      freezed:
        options:
          map: false
          when:
            when: true
            maybe_when: true
            when_or_null: false
      source_gen|combining_builder:
        options:
          explicit_to_json: false
          ignore_for_file:
            - type=lint
            - implicit_dynamic_parameter
            - implicit_dynamic_type
            - implicit_dynamic_method
            - strict_raw_type