name: amasearch
description: Amazon Item Seach Tool

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.6.0+9999

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  adaptive_dialog: ^1.9.0+2
  archive: ^3.3.8
  cloud_functions: ^4.3.3
  collection: ^1.17.2
  convert: ^3.1.1
  cookie_jar: ^4.0.8
  crypto: ^3.0.3
  csv: ^5.0.2
  cupertino_icons: ^1.0.6
  dartx: ^1.2.0
  device_info_plus: ^9.0.3
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.0+1
  euc:
    path: ./packages/euc
  extended_image: ^8.1.1
  fast_barcode_scanner:
    path: ./packages/fast_barcode_scanner/fast_barcode_scanner
  file_picker: ^5.5.0
  firebase_analytics: ^10.4.3
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.3
  firebase_performance: ^0.9.2+3
  firebase_remote_config: ^4.2.3
  firebase_storage: ^11.2.3
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_hooks: ^0.20.1
  flutter_inappwebview: ^6.0.0-beta.24+1
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  flutter_signin_button: ^2.0.0
  flutter_slidable: ^3.0.0
  flutter_speed_dial: ^7.0.0
  flutter_tts: ^3.8.2
  flutter_typeahead: ^4.6.2
  freezed_annotation: ^2.4.1
  google_sign_in: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.4.0
  html: ^0.15.4
  image_editor: ^1.3.0
  in_app_review: ^2.0.6
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  keyboard_actions: ^4.2.0
  package_info_plus: ^4.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^10.4.5
  pub_semver: ^2.1.4
  purchases_flutter: ^5.6.5
  reactive_date_range_picker: ^2.0.0
  reactive_forms: ^16.1.0
  release_notes_dialog: ^2.0.0
  reorderables: ^0.6.0
  riverpod: ^2.4.0
  share_plus: ^7.1.0
  shared_preferences: ^2.2.1
  state_notifier: ^1.0.0
  url_launcher: ^6.1.14
  uuid: ^3.0.7
  vibration: ^1.8.1
  webview_flutter: ^4.2.4
  worker_manager: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  hive_generator: ^2.0.1
  pedantic_mono: ^1.24.0+1

dependency_overrides:
  extended_image_library:
    path: ./packages/extended_image_library

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon2.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#d8ad7e"
  adaptive_icon_foreground: "assets/adaptive_icon_foreground2.png"
  min_sdk_android: 28

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#d8ad7e"
  image: assets/splash_icon2.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/title_b2.png
    - assets/locked_small.png
    - assets/keepa_sample.png
    - assets/faq/plan.png
    - assets/faq/cache.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages