name: amasearch
description: Amazon Item Seach Tool

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.9.6+9999

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  adaptive_dialog: ^1.8.2
  archive: ^3.3.6
  cloud_functions: ^4.0.11
  collection: ^1.17.0
  convert: ^3.1.1
  cookie_jar: ^3.0.1
  crypto: ^3.0.2
  csv: ^5.0.1
  cupertino_icons: ^1.0.5
  dartx: ^1.1.0
  device_info_plus: ^8.1.0
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  euc:
    path: ./packages/euc
  extended_image: ^6.3.4
  fast_barcode_scanner:
    path: ./packages/fast_barcode_scanner/fast_barcode_scanner
  firebase_analytics: ^10.1.3
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0
  firebase_crashlytics: ^3.0.14
  firebase_performance: ^0.9.0+11
  firebase_remote_config: ^3.0.10
  firebase_storage: ^11.0.11
  flex_color_scheme: ^4.2.0
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_hooks: ^0.18.5+1
  flutter_launcher_icons: ^0.11.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.16
  flutter_signin_button: ^2.0.0
  flutter_slidable: ^2.0.0
  flutter_speed_dial: ^6.2.0
  flutter_tts: ^3.6.3
  flutter_typeahead: ^4.3.3
  flutter_web_browser: ^0.17.1
  freezed_annotation: ^2.2.0
  google_sign_in: ^5.4.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.2.0
  html: ^0.15.1
  in_app_review: ^2.0.6
  intl: ^0.17.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  keyboard_actions: ^4.1.0
  package_info_plus: ^3.0.3
  path: ^1.8.2
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  pub_semver: ^2.1.3
  purchases_flutter: ^4.9.1
  reactive_date_range_picker: ^0.5.0
  reactive_forms: ^14.1.0
  release_notes_dialog: ^1.1.0
  riverpod: ^2.2.0
  share_plus: ^6.3.1
  shared_preferences: ^2.0.17
  state_notifier: ^0.7.2+1
  url_launcher: ^6.1.9
  uuid: ^3.0.7
  vibration: ^1.7.6
  webview_flutter: ^3.0.4
  worker_manager: ^5.0.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  pedantic_mono: ^1.21.1

dependency_overrides:
  extended_image_library:
    path: ./packages/extended_image_library

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon2.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#d8ad7e"
  adaptive_icon_foreground: "assets/adaptive_icon_foreground2.png"
  min_sdk_android: 28

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#d8ad7e"
  image: assets/splash_icon2.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/title_b2.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages