name: amasearch
description: Amazon Item Seach Tool

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.1+9999

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  adaptive_dialog: ^1.3.0
  ai_barcode:
    path: ./packages/ai_barcode
  camera: ^0.9.4+6 # https://github.com/flutter/flutter/issues/90070 待ち
  cloud_functions: ^3.2.9
  collection: ^1.15.0
  cookie_jar: ^3.0.1
  crypto: ^3.0.1
  csv: ^5.0.1
  cupertino_icons: ^1.0.4
  device_info_plus: ^3.2.2
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0
  euc:
    path: ./packages/euc
  extended_image: ^6.0.1
  fast_barcode_scanner:
    path: ./packages/fast_barcode_scanner/fast_barcode_scanner
  firebase_analytics: ^9.1.2
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  firebase_crashlytics: ^2.5.3
  firebase_performance: ^0.8.0+7
  firebase_remote_config: ^2.0.2
  flex_color_scheme: ^4.2.0
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.3
  flutter_hooks: ^0.18.2+1
  flutter_launcher_icons: ^0.9.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.0.5
  flutter_signin_button: ^2.0.0
  flutter_slidable: ^1.2.0
  flutter_tts: ^3.3.3
  flutter_web_browser: ^0.17.0
  freezed_annotation: ^1.1.0
  google_ml_kit: ^0.7.3
  google_sign_in: ^5.2.4
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  hooks_riverpod: 1.0.3
  html: ^0.15.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  keyboard_actions: 3.4.4 # https://github.com/diegoveloper/flutter_keyboard_actions/commit/2960caade1d0347f1d7a0f79b32405b3c4310ca1 のリリース待ち
  package_info_plus: ^1.4.0
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  pub_semver: ^2.1.0
  purchases_flutter: ^3.9.5
  reactive_forms: ^11.0.1
  reactive_touch_spin: ^0.4.1
  riverpod: 1.0.3
  share: ^2.0.4
  shared_preferences: ^2.0.13
  sign_in_with_apple: ^3.3.0
  state_notifier: ^0.7.2+1
  url_launcher: ^6.0.20
  uuid: ^3.0.6
  vibration: ^1.7.4-nullsafety.0
  webview_flutter: ^3.0.1

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  hive_generator: ^1.1.2
  pedantic_mono: ^1.17.0

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon2.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#d8ad7e"
  adaptive_icon_foreground: "assets/adaptive_icon_foreground2.png"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#d8ad7e"
  image: assets/splash_icon2.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/title_b2.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages