// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxeIVnLgUFV4G9_cPeKPz3GDFSU26Mdo4',
    appId: '1:890414837237:android:210b2d070003e5936304bc',
    messagingSenderId: '890414837237',
    projectId: 'amasearch-stg',
    databaseURL: 'https://amasearch-stg.firebaseio.com',
    storageBucket: 'amasearch-stg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOvURwptjfVsWUN9XbB9oOhUdkKap1gYQ',
    appId: '1:890414837237:ios:2eb510c1796f6aa16304bc',
    messagingSenderId: '890414837237',
    projectId: 'amasearch-stg',
    databaseURL: 'https://amasearch-stg.firebaseio.com',
    storageBucket: 'amasearch-stg.appspot.com',
    androidClientId:
        '890414837237-pcjapdpulkd5ejsl0bgdo2h7q6dgfvjq.apps.googleusercontent.com',
    iosClientId:
        '890414837237-vv0qnqmd05bt72oc87avbpbah12hd749.apps.googleusercontent.com',
    iosBundleId: 'com.knzc.amasearch',
  );
}
