// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDic6Tq2iNdNul96ANwxUNKQ2-LKv3FfA0',
    appId: '1:157832618677:android:e735ed55f67c4d0b5e94fc',
    messagingSenderId: '157832618677',
    projectId: 'amasearch-live',
    storageBucket: 'amasearch-live.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuuYO-jf8jIsMsniXTPbvp3oZG0LFvMbI',
    appId: '1:157832618677:ios:cc1af2f27de351a75e94fc',
    messagingSenderId: '157832618677',
    projectId: 'amasearch-live',
    storageBucket: 'amasearch-live.appspot.com',
    androidClientId:
        '157832618677-k59hftqap3fudgsaoqa0b37fa00c2bcq.apps.googleusercontent.com',
    iosClientId:
        '157832618677-i9v4vujc1tj51dtk9mgqvu735ngc3btf.apps.googleusercontent.com',
    iosBundleId: 'com.knzc.app.amasearch',
  );
}
