version: "3.8"
networks:
  backend:

x-environment: &deploy-proj-env
  DEPLOY_REGION: asia-northeast1

x-firebase-volume: &firebase-volume
  - rakupo-firebase-volume:/root/.config
  - ./:/app
  - /app/node_modules

services:
  website:
    build:
      context: .
      dockerfile: Dockerfile_release
    environment: *deploy-proj-env
    volumes: *firebase-volume
    tty: true
    command: sh -c "yarn install && yarn build && find ./out -name *.map -delete && mv out/404/index.html out/404.html && firebase deploy --project $$DEPLOY_PROJECT"

volumes:
  rakupo-firebase-volume:
    external: true
